import { z } from "zod";

const emptyToUndefined = (value: unknown): unknown =>
  typeof value === "string" && value.trim() === "" ? undefined : value;

const optionalTrimmedString = (maximum: number) =>
  z.preprocess(emptyToUndefined, z.string().trim().max(maximum).optional());

function isPostgresUrl(value: string): boolean {
  try {
    const url = new URL(value);
    return url.protocol === "postgres:" || url.protocol === "postgresql:";
  } catch {
    return false;
  }
}

function hasValidEncryptionKeyLength(value: string): boolean {
  try {
    if (/^[a-f0-9]{64}$/i.test(value)) return true;
    const normalized = value.replace(/-/g, "+").replace(/_/g, "/");
    return Buffer.from(normalized, "base64").length === 32;
  } catch {
    return false;
  }
}

const serverEnvSchema = z
  .object({
    NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
    DATABASE_URL: z.string().trim().refine(isPostgresUrl, "DATABASE_URL must be a Postgres URL."),
    ADMIN_PASSWORD_HASH: z
      .string()
      .trim()
      .regex(
        /^scrypt\$v1\$\d+\$\d+\$\d+\$[A-Za-z0-9_-]+\$[A-Za-z0-9_-]+$/,
        "ADMIN_PASSWORD_HASH must be generated by the provided script.",
      ),
    SESSION_SECRET: z.string().min(32).max(1_024),
    APP_ENCRYPTION_KEY: z
      .string()
      .trim()
      .refine(hasValidEncryptionKeyLength, "APP_ENCRYPTION_KEY must decode to exactly 32 bytes."),
    CRON_SECRET: z.string().min(16).max(1_024),
    GEMINI_API_KEY: optionalTrimmedString(1_024),
    RESEND_API_KEY: optionalTrimmedString(1_024),
    RESEND_FROM: optionalTrimmedString(320),
    SESSION_TTL_HOURS: z.coerce.number().int().min(1).max(168).default(24),
    VERCEL_CRON_PROFILE: z.enum(["hobby", "pro"]).default("hobby"),
    OWNER_EMAIL: z.preprocess(emptyToUndefined, z.string().trim().email().max(254).optional()),
    OWNER_NAME: optionalTrimmedString(80),
  })
  .passthrough();

export interface ServerEnv {
  nodeEnv: "development" | "test" | "production";
  databaseUrl: string;
  adminPasswordHash: string;
  sessionSecret: string;
  appEncryptionKey: string;
  cronSecret: string;
  geminiApiKey?: string;
  resendApiKey?: string;
  resendFrom?: string;
  sessionTtlHours: number;
  cronProfile: "hobby" | "pro";
  schedulerMinIntervalHours: 1 | 24;
  ownerEmail?: string;
  ownerName?: string;
}

let cachedEnv: ServerEnv | null = null;

export function getServerEnv(source: NodeJS.ProcessEnv = process.env): ServerEnv {
  if (typeof window !== "undefined") {
    throw new Error("Server configuration must not be accessed from the browser.");
  }
  if (source === process.env && cachedEnv) return cachedEnv;

  const parsed = serverEnvSchema.parse(source);
  const value: ServerEnv = {
    nodeEnv: parsed.NODE_ENV,
    databaseUrl: parsed.DATABASE_URL,
    adminPasswordHash: parsed.ADMIN_PASSWORD_HASH,
    sessionSecret: parsed.SESSION_SECRET,
    appEncryptionKey: parsed.APP_ENCRYPTION_KEY,
    cronSecret: parsed.CRON_SECRET,
    geminiApiKey: parsed.GEMINI_API_KEY,
    resendApiKey: parsed.RESEND_API_KEY,
    resendFrom: parsed.RESEND_FROM,
    sessionTtlHours: parsed.SESSION_TTL_HOURS,
    cronProfile: parsed.VERCEL_CRON_PROFILE,
    schedulerMinIntervalHours: parsed.VERCEL_CRON_PROFILE === "pro" ? 1 : 24,
    ownerEmail: parsed.OWNER_EMAIL,
    ownerName: parsed.OWNER_NAME,
  };

  if (source === process.env) cachedEnv = value;
  return value;
}

export function resetServerEnvCacheForTests(): void {
  cachedEnv = null;
}
